version: "3.9"
name: default
services:
  nginx_default:
    container_name: nginx_default
    image: nginx:1.17.8
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../:/var/www
    links:
      - php_default
  php_default:
    container_name: php_default
    build: ./php
    working_dir: /var/www
    volumes:
      - ../:/var/www
